trigger:
- main

parameters:
- name: selectedEnv
  displayName: 'Select Environment'
  type: string
  default: dev
  values:
  - dev
  - qa
  - stg
  - prd

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'
  pool:
    name: gor-platform-agents-aca-${{ parameters.selectedEnv }}
  steps:
  - script: |
      echo "Building and deploying to the ${{ parameters.selectedEnv  }} environment using the gor-platform-agents-aca-${{ parameters.selectedEnv  }} agent pool."
    displayName: 'Execute Build and Deployment Script'
