# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: selectedEnv
    type: string
    default: dev
    displayName: 'Select Environment'
    values:
      - dev
      - qa
      - stg
      - prd

jobs:
- job: MultiEnvironmentBuild
  strategy:
    matrix:
      aca:
        AGENT_POOL: 'gor-platform-agents-aca-$(parameters.selectedEnv)'
  pool:
    name: $(AGENT_POOL)

  steps:
  - script: |
      echo "Running build on $(AGENT_POOL)"
    displayName: 'Run build on different environments'
